USE Recipe
GO
/*
 --CLUSTERED
--Unique

CREATE CLUSTERED INDEX ID_INDEX 
ON Rating(ID_raiting)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_raiting > 100

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ID_INDEX ON Rating

--Composite

CREATE CLUSTERED INDEX ID_IDUSER_INDEX 
ON Rating(ID_raiting,ID_user)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting,ID_user FROM Rating
WHERE ID_raiting IN(4,899) AND ID_user > 1

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ID_IDUSER_INDEX ON Rating


--Covering

CREATE CLUSTERED INDEX ALL_INDEX
ON Rating(ID_raiting,ID_user,Recipes_count,Positive_per,Negative_per)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_user > 1 AND (Positive_per >= 50 AND Negative_per < 50)

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ALL_INDEX ON Rating


*/
--NONCLUSTERED

--Unique
/*
CREATE NONCLUSTERED INDEX ID_INDEX
ON Rating(ID_raiting)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting FROM Rating
WHERE ID_raiting > 100

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
*/
--Composite
/*
CREATE NONCLUSTERED INDEX ID_IDUSER_INDEX 
ON Rating(ID_raiting,ID_user)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting,ID_user FROM Rating
WHERE ID_raiting IN(4,899) AND ID_user > 1

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ID_IDUSER_INDEX ON Rating


--Covering

CREATE NONCLUSTERED INDEX ALL_INDEX
ON Rating(ID_raiting,ID_user,Recipes_count,Positive_per,Negative_per)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_user > 1 AND (Positive_per >= 50 AND Negative_per < 50)

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
DROP INDEX ALL_INDEX ON Rating


--Including tables

CREATE NONCLUSTERED INDEX INCLTA
ON Rating(ID_raiting,ID_user)
INCLUDE(Recipes_count)

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating WHERE Recipes_count BETWEEN 250 and 900

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;*/