USE Recipe
GO

  --CLUSTERED
--Unique
/*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_raiting > 100

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

*/
--Composite
/*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting,ID_user FROM Rating
WHERE ID_raiting IN(4,899) AND ID_user > 1

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

*/
--Covering
 /*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_user > 1 AND (Positive_per >= 50 AND Negative_per < 50)

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

*/
--NONCLUSTERED

SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting FROM Rating
WHERE ID_raiting > 100

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;

--Composite
/*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT ID_raiting,ID_user FROM Rating
WHERE ID_raiting IN(4,899) AND ID_user > 1

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
*/

--Covering
/*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating
WHERE ID_user > 1 AND (Positive_per >= 50 AND Negative_per < 50)

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;
*/

--Including tables
/*
SET STATISTICS IO ON;
SET STATISTICS TIME ON;

SELECT * FROM Rating WHERE Recipes_count BETWEEN 250 and 900 

SET STATISTICS IO OFF;
SET STATISTICS TIME OFF;*/